### ISSUE TITLE
[瞎扯] 白沙不完整导航

### ISSUE THREAD

**Issue by d1y** [luxizhizhong/share#2]
## 修车地方
> 桥头宾馆,我没有去过的,只要是个白沙人就都知道,不过貌似都有点丑
![](https://i.loli.net/2019/03/06/5c7f2238f0ec0.png)

> http://j.map.baidu.com/XQUSe

## 网吧推荐
- 曼城: 离学校最近的曼城还行,机子比较新,显示器比较大,但是如果是学习的,它那边可能不是最好的选择
- 欢乐谷: 这个网吧,我个人觉得还行,比较安静,然后也比较适合学习,我个人曾经一直都是在那里,不过网络和机子都比较垃圾
- 星源: 在医院旁边,这里机子比较少,但是配的是`win10`,网速也还行,不过如果在这里学习的,不太好,而且这里环境不好,厕所常年有人
- 环宇: 菜市场那边,还行,就是厕所太不卫生了,这里机子比较多,感觉还行吧,学习的话,也可以
- 阳光: 车站那边,还行,就是网速不太好,而且键盘也太油了吧,学习的话,我曾经在那里翻车过,那网管是个人才,个人建议不要在那里学习(额,曾经在那里开了个`linux-live`环境,然后就发现网管在后面一直看我操作,吓得半死)
- 伊妹儿: 厕所比前几个好一点,网速好,不过就是吸烟的人特别多,学习的话,可能你学不下去,人太多了,太吵了

## 妹子推荐
建议去河边暗中观察,会有妹子的,建议尾随别人妹子(2333),应该会有很多妹子的

**Comment by MrYang-Web** [comment]
什么叫白沙人都知道修车的地方.....我怎么不知道?

老司机带带我!!!!
